const ecuadorLocations = {
  Azuay: {
    Cuenca: [
      "Cuenca",
      "Baños",
      "Cumbe",
      "Chaucha",
      "Checa",
      "Chiquintad",
      "Llacao",
      "Molleturo",
      "Nulti",
      "Octavio Cordero Palacios",
      "Paccha",
      "Quingeo",
      "Ricaurte",
      "San Joaquín",
      "Santa Ana",
      "Sayausí",
      "Sidcay",
      "Sinincay",
      "Tarqui",
      "Turi",
      "Valle",
      "Victoria del Portete",
    ],
    Girón: ["Girón", "Asunción", "San Gerardo"],
    Gualaceo: [
      "Gualaceo",
      "Jadán",
      "Mariano Moreno",
      "Remigio Crespo",
      "San Juan",
      "Shagli",
      "Zhidmad",
      "Daniel Córdova Toral",
      "Luis Cordero Vega",
      "Simón Bolívar",
    ],
    Nabón: ["Nabón", "Cochapata", "El Progreso", "Las Nieves"],
    Paute: [
      "Paute",
      "Amaluza",
      "Bulán",
      "Chican",
      "El Cabo",
      "Guachapala",
      "San Cristóbal",
      "Sevilla de Oro",
      "Tomebamba",
      "Dugdug",
    ],
    Pucará: ["Pucará", "Camilo Ponce Enríquez", "San Rafael de Sharug"],
    "San Fernando": ["San Fernando", "Chumblín"],
    "Santa Isabel": [
      "Santa Isabel",
      "Abdón Calderón",
      "El Carmen de Pijilí",
      "Zhaglli",
    ],
    Sigsig: [
      "Sigsig",
      "Cuchil",
      "Guel",
      "Ludo",
      "San Bartolomé",
      "San José de Raranga",
    ],
    Oña: ["Oña", "Susudel"],
    Chordeleg: [
      "Chordeleg",
      "Delegsol",
      "Luis Galarza Orellana",
      "San Martín de Puzhio",
    ],
    "El Pan": ["El Pan", "San Vicente"],
    "Sevilla de Oro": ["Sevilla de Oro", "Amaluza", "Palmas"],
    Guachapala: ["Guachapala"],
    "Camilo Ponce Enríquez": ["Camilo Ponce Enríquez", "El Carmen de Pijilí"],
  },

  Bolívar: {
    Guaranda: [
      "Guaranda",
      "Facundo Vela",
      "Guanujo",
      "Julio Moreno",
      "Salinas",
      "San Lorenzo",
      "San Simón",
      "Santa Fe",
    ],
    Chillanes: ["Chillanes", "San José del Tambo"],
    Chimbo: [
      "Chimbo",
      "Asunción",
      "Magdalena",
      "San José de Chimbo",
      "San Sebastián",
      "Telimbela",
    ],
    Echeandía: ["Echeandía"],
    "San Miguel": [
      "San Miguel",
      "Balsapamba",
      "Bilován",
      "Régulo de Mora",
      "San Pablo",
      "Santiago",
    ],
    Caluma: ["Caluma"],
    "Las Naves": ["Las Naves"],
  },

  Cañar: {
    Azogues: [
      "Azogues",
      "Aurelio Bayas Martínez",
      "Cojitambo",
      "Déleg",
      "Guapán",
      "Javier Loyola",
      "Luis Cordero",
      "Pindilig",
      "Rivera",
      "San Francisco",
      "Taday",
    ],
    Biblián: [
      "Biblián",
      "Nazón",
      "San Francisco de Sageo",
      "Turupamba",
      "Zhud",
    ],
    Cañar: [
      "Cañar",
      "Chontamarca",
      "Chorocopte",
      "General Morales",
      "Gualleturo",
      "Honorato Vásquez",
      "Ingapirca",
      "Juncal",
      "San Antonio",
      "Ventura",
      "Zhud",
    ],
    "La Troncal": ["La Troncal", "Manuel J. Calle", "Pancho Negro"],
    "El Tambo": ["El Tambo"],
    Déleg: ["Déleg", "Solano"],
    Suscal: ["Suscal"],
  },

  Carchi: {
    Tulcán: [
      "Tulcán",
      "El Carmelo",
      "Huaca",
      "Julio Andrade",
      "Maldonado",
      "Pioter",
      "Tobar Donoso",
      "Tufiño",
      "Urbina",
    ],
    Bolívar: [
      "Bolívar",
      "García Moreno",
      "Los Andes",
      "Monte Olivo",
      "San Rafael",
      "San Vicente de Pusir",
    ],
    Espejo: ["El Angel", "El Goaltal", "La Libertad", "San Isidro"],
    Mira: ["Mira", "Concepción", "Jijón y Caamaño", "Juan Montalvo"],
    Montúfar: [
      "San Gabriel",
      "Cristóbal Colón",
      "Chitán de Navarrete",
      "Fernández Salvador",
      "La Paz",
      "Piartal",
    ],
    "San Pedro de Huaca": ["Huaca", "Mariscal Sucre"],
  },

  Cotopaxi: {
    Latacunga: [
      "Latacunga",
      "Aláquez",
      "Belisario Quevedo",
      "Guaytacama",
      "Joseguango Bajo",
      "Mulaló",
      "Once de Noviembre",
      "Poaló",
      "San Juan de Pastocalle",
      "Sigchos",
      "Tanicuchí",
      "Toacaso",
    ],
    "La Maná": ["La Maná", "El Triunfo", "Guasaganda", "Pucayacu"],
    Pangua: ["El Corazón", "Moraspungo", "Pinllopata", "Ramón Campaña"],
    Pujilí: [
      "Pujilí",
      "Angamarca",
      "Chucchilán",
      "Guangaje",
      "Isinlibí",
      "José Guango Bajo",
      "La Victoria",
      "Pilaló",
      "Tingo",
      "Zumbahua",
    ],
    Salcedo: [
      "San Miguel",
      "Antonio José Holguín",
      "Cusubamba",
      "Mulliquindil",
      "Mulalillo",
      "Panzaleo",
    ],
    Saquisilí: ["Saquisilí", "Canchagua", "Chantilín", "Cochapamba"],
    Sigchos: [
      "Sigchos",
      "Chugchillán",
      "Isinliví",
      "Las Pampas",
      "Palo Quemado",
    ],
  },

  Chimborazo: {
    Riobamba: [
      "Riobamba",
      "Cacha",
      "Calpi",
      "Cubijíes",
      "Flores",
      "Licán",
      "Licto",
      "Pungalá",
      "Punín",
      "Quimiag",
      "San Juan",
      "San Luis",
      "Yaruquíes",
    ],
    Alausí: [
      "Alausí",
      "Achupallas",
      "Cumandá",
      "Guasuntos",
      "Huigra",
      "Multitud",
      "Pistishi",
      "Pumallacta",
      "Sevilla",
      "Sibambe",
      "Tixán",
    ],
    Colta: [
      "Villa La Unión",
      "Cajabamba",
      "Columbe",
      "Juan de Velasco",
      "Santiago de Quito",
    ],
    Chambo: ["Chambo"],
    Chunchi: ["Chunchi", "Capzol", "Compud", "Gonzol", "Llagos"],
    Guamote: ["Guamote", "Cebadas", "Palmira"],
    Guano: [
      "Guano",
      "La Providencia",
      "San Andrés",
      "San Gerardo de Pachanillay",
      "San José del Chazo",
      "San Isidro de Patulú",
      "Santa Fe de Galán",
      "Valparaíso",
    ],
    Pallatanga: ["Pallatanga"],
    Penipe: ["Penipe", "El Altar", "La Candelaria", "Matus", "Puela", "Bilbao"],
    Cumandá: ["Cumandá"],
  },

  "El Oro": {
    Machala: [
      "Machala",
      "El Cambio",
      "El Retiro",
      "Nueve de Mayo",
      "Puerto Bolívar",
      "La Providencia",
    ],
    Arenillas: ["Arenillas", "Chacras", "La Libertad", "Las Lajas", "Palmales"],
    Atahualpa: ["Paccha", "Ayapamba", "Cordoncillo", "Milagro", "San José"],
    Balsas: ["Balsas", "Bellamaría"],
    Chilla: ["Chilla"],
    "El Guabo": ["El Guabo", "Barbones", "La Iberia", "Tendales", "Río Bonito"],
    Huaquillas: ["Huaquillas", "Ecuador", "El Paraíso"],
    Marcabelí: ["Marcabelí", "El Ingenio"],
    Pasaje: [
      "Pasaje",
      "Buenavista",
      "Casacay",
      "La Peaña",
      "Loma de Franco",
      "Ochoa León",
      "Progreso",
      "San Antonio",
      "Tres Cerritos",
      "Cañaquemada",
    ],
    Piñas: [
      "Piñas",
      "Capiro",
      "La Bocana",
      "La Susaya",
      "Moromoro",
      "Piedras",
      "San Roque",
      "Saracay",
    ],
    Portovelo: ["Portovelo", "Curtincapa", "Morales", "Salatí"],
    "Santa Rosa": [
      "Santa Rosa",
      "Bellavista",
      "Jambelí",
      "La Avanzada",
      "San Antonio",
      "Torata",
      "Victoria",
      "Bellamaría",
    ],
    Zaruma: [
      "Zaruma",
      "Abañín",
      "Arcapamba",
      "Guanazán",
      "Guizhaguiña",
      "Huertas",
      "Malvas",
      "Muluncay Gránde",
      "Sinsao",
      "Salvias",
    ],
    "Las Lajas": ["La Victoria", "San Isidro"],
    // eslint-disable-next-line no-dupe-keys
    Chilla: ["Chilla"],
  },

  Esmeraldas: {
    Esmeraldas: [
      "Esmeraldas",
      "Bartolomé Ruiz",
      "Carlos Concha Torres",
      "Chinca",
      "Crnel. Carlos Concha Torres",
      "Majua",
      "San Mateo",
      "Tachina",
      "Vuelta Larga",
      "Tabiazo",
    ],
    "Eloy Alfaro": [
      "Valdez",
      "Anchayacu",
      "Atahualpa",
      "Borbón",
      "La Tola",
      "Luis Vargas Torres",
      "Maldonado",
      "Pampanal de Bolívar",
      "San Francisco de Onzole",
      "Santo Domingo de Onzole",
      "Selva Alegre",
      "Telembí",
      "Timbiré",
      "Colón Eloy del María",
    ],
    Muisne: [
      "Muisne",
      "Bolívar",
      "Daule",
      "Galera",
      "Quingue",
      "Salima",
      "San Francisco",
      "San Gregorio",
      "San José de Chamanga",
    ],
    Quinindé: ["Rosa Zárate", "Cube", "Chura", "Malimpia", "Viche", "La Unión"],
    "San Lorenzo": [
      "San Lorenzo",
      "Alto Tambo",
      "Ancón",
      "Calderón",
      "Carondelet",
      "5 de Junio",
      "Santa Rita",
      "Tambillo",
      "Tululbí",
      "Urbina",
    ],
    Atacames: ["Atacames", "La Unión", "Súa", "Tonchigüe", "Tonsupa"],
    Rioverde: ["Rioverde", "Chontaduro", "Lagarto", "Montalvo", "Rocafuerte"],
  },

  Guayas: {
    Guayaquil: [
      "Guayaquil",
      "Posorja",
      "Puna",
      "Tenguel",
      "Morro",
      "Juan Gómez Rendón",
      "Progreso",
      "Puná",
      "El Morro",
    ],
    "Alfredo Baquerizo Moreno": ["Alfredo Baquerizo Moreno"],
    Balao: ["Balao"],
    Balzar: ["Balzar"],
    Colimes: ["Colimes", "San Jacinto"],
    Daule: [
      "Daule",
      "Banife",
      "Emiliano Ortiz Bejarano",
      "Juan Bautista Aguirre",
      "Laurel",
      "Limonal",
      "Los Lojas",
      "Piedrahita",
      "Santa Clara",
    ],
    Durán: ["Durán", "Eloy Alfaro"],
    "El Empalme": ["Velasco Ibarra", "Guayas", "El Rosario"],
    "El Triunfo": ["El Triunfo"],
    Milagro: [
      "Milagro",
      "Chobo",
      "General Elizalde",
      "Mariscal Sucre",
      "Roberto Astudillo",
    ],
    Naranjal: [
      "Naranjal",
      "Jesús María",
      "San Carlos",
      "Santa Rosa de Flandes",
      "Taura",
    ],
    Naranjito: ["Naranjito"],
    Palestina: ["Palestina"],
    "Pedro Carbo": ["Pedro Carbo", "Sabanilla", "Valle de la Virgen"],
    Samborondón: ["Samborondón", "Tarifa", "La Puntilla"],
    "Santa Lucía": ["Santa Lucía"],
    Salitre: ["Salitre", "General Vernaza", "Junquillal", "La Victoria"],
    "San Jacinto de Yaguachi": [
      "Yaguachi Nuevo",
      "Yaguachi Viejo",
      "Virgen de Fátima",
      "General Pedro J. Montero",
      "Cone",
    ],
    Playas: ["General Villamil", "El Morro"],
    "Simón Bolívar": ["Simón Bolívar", "Crnel. Lorenzo de Garaicoa"],
    "Crnel. Marcelino Maridueña": ["Crnel. Marcelino Maridueña"],
    "Lomas de Sargentillo": ["Lomas de Sargentillo"],
    Nobol: ["Narcisa de Jesús"],
    "General Antonio Elizalde": ["Bucay"],
    "Isidro Ayora": ["Isidro Ayora"],
  },

  Imbabura: {
    Ibarra: [
      "Ibarra",
      "Ambuquí",
      "Angochagua",
      "Carolina",
      "La Esperanza",
      "Lita",
      "Salinas",
      "San Antonio",
    ],
    "Antonio Ante": [
      "Atuntaqui",
      "Andrade Marín",
      "Chaltura",
      "Imbaya",
      "San Francisco de Natabuela",
      "San José de Chaltura",
      "San Roque",
    ],
    Cotacachi: [
      "Cotacachi",
      "Apuela",
      "García Moreno",
      "Imantag",
      "Peñaherrera",
      "Plaza Gutiérrez",
      "Quiroga",
      "6 de Julio de Cuellaje",
      "Vacas Galindo",
    ],
    Otavalo: [
      "Otavalo",
      "Dr. Miguel Egas Cabezas",
      "Eugenio Espejo",
      "González Suárez",
      "Pataquí",
      "San José de Quichinche",
      "San Juan de Ilumán",
      "San Pablo",
      "San Rafael",
      "Selva Alegre",
    ],
    Pimampiro: [
      "Pimampiro",
      "Chuga",
      "Mariano Acosta",
      "San Francisco de Sigsipamba",
    ],
    "San Miguel de Urcuquí": [
      "Urcuquí",
      "Cahuasquí",
      "La Merced de Buenos Aires",
      "Pablo Arenas",
      "San Blas",
      "Tumbabiro",
    ],
  },

  Loja: {
    Loja: [
      "Loja",
      "Chantaco",
      "Chuquiribamba",
      "El Cisne",
      "Gualel",
      "Jimbilla",
      "Malacatos",
      "San Lucas",
      "San Pedro de Vilcabamba",
      "Santiago",
      "Taquil",
      "Vilcabamba",
      "Yangana",
    ],
    Calvas: [
      "Cariamanga",
      "Chile",
      "Colaisaca",
      "El Lucero",
      "Sanguillín",
      "Utuana",
    ],
    Catamayo: [
      "Catamayo",
      "Guayquichuma",
      "San José",
      "San Pedro de la Bendita",
      "Zambi",
    ],
    Celica: [
      "Celica",
      "Cruzpamba",
      "Pindal",
      "Pózul",
      "Sabanilla",
      "Tnte. Maximiliano Rodríguez Loaiza",
    ],
    Chaguarpamba: ["Chaguarpamba", "Buenavista", "El Rosario", "Santa Rufina"],
    Espíndola: [
      "Amaluza",
      "Bellavista",
      "El Airo",
      "El Ingenio",
      "Jimbura",
      "Santa Teresita",
      "27 de Abril",
    ],
    Gonzanamá: [
      "Gonzanamá",
      "Changaimina",
      "Nambacola",
      "Purunuma",
      "Sacapalca",
    ],
    Macará: ["Macará", "Larama", "La Victoria", "Sabiango"],
    Paltas: [
      "Catacocha",
      "Cangonamá",
      "Guachanamá",
      "Lauro Guerrero",
      "Orianga",
      "San Antonio",
      "Casanga",
      "Yamana",
    ],
    Puyango: [
      "Alamor",
      "Ciano",
      "El Arenal",
      "El Limo",
      "Mercadillo",
      "Vicentino",
    ],
    Saraguro: [
      "Saraguro",
      "El Paraíso de Celén",
      "El Tablón",
      "Lluzhapa",
      "Manú",
      "San Antonio de Qumbe",
      "San Pablo de Tenta",
      "San Sebastián de Yúluc",
      "Selva Alegre",
      "Sumaypamba",
      "Urdaneta",
    ],
    Sozoranga: ["Sozoranga", "Nueva Fátima", "Tacamoros"],
    Zapotillo: [
      "Zapotillo",
      "Bolaspamba",
      "Garza Real",
      "Limones",
      "Paletillas",
    ],
    Pindal: ["Pindal", "12 de Diciembre", "Chaquinal", "Milagros"],
    Quilanga: ["Quilanga", "Fundochamba", "San Antonio de las Aradas"],
    Olmedo: ["Olmedo", "La Tingue"],
  },

  "Los Ríos": {
    Babahoyo: [
      "Babahoyo",
      "Camilo Ponce",
      "Caracol",
      "Febres Cordero",
      "Pimocha",
      "La Unión",
    ],
    Baba: ["Baba", "Guare", "Isla de Bejucal"],
    Montalvo: ["Montalvo"],
    Puebloviejo: ["Puebloviejo", "Puerto Pechiche", "San Juan"],
    Quevedo: [
      "Quevedo",
      "24 de Mayo",
      "Buena Fe",
      "Guayacán",
      "Nicolás Infante Díaz",
      "San Camilo",
      "San Carlos",
      "San José",
      "Seven de Octubre",
      "Viva Alfaro",
      "Venus",
    ],
    Urdaneta: ["Catarama", "Ricaurte"],
    Ventanas: ["Ventanas", "Zapotal"],
    Vinces: ["Vinces", "Antonio Sotomayor"],
    Palenque: ["Palenque"],
    "Buena Fe": ["Buena Fe", "Patricia Pilar", "11 de Octubre"],
    Valencia: ["Valencia"],
    Mocache: ["Mocache"],
    Quinsaloma: ["Quinsaloma"],
  },

  Manabí: {
    Portoviejo: [
      "Portoviejo",
      "Abdón Calderón",
      "Alhajuela",
      "Chirijos",
      "Pueblo Nuevo",
      "Riochico",
      "San Plácido",
      "Río Chico",
    ],
    Bolívar: ["Bolívar", "Calceta", "Membrillo", "Quiroga"],
    Chone: [
      "Chone",
      "Boyacá",
      "Canuto",
      "Convento",
      "Chibunga",
      "Eloy Alfaro",
      "Ricaurte",
      "San Antonio",
      "Santa Rita",
    ],
    "El Carmen": ["El Carmen"],
    "Flavio Alfaro": ["Flavio Alfaro", "San Francisco de Novillo", "Zapallo"],
    Jipijapa: [
      "Jipijapa",
      "América",
      "El Anegado",
      "Julcuy",
      "La Unión",
      "Membrillal",
      "Pedro Pablo Gómez",
      "Puerto Cayo",
      "Puerto de Cayo",
    ],
    Junín: ["Junín"],
    Manta: [
      "Manta",
      "Eloy Alfaro",
      "Los Esteros",
      "Manta",
      "San Mateo",
      "Santa Marianita",
      "Tarqui",
    ],
    Montecristi: [
      "Montecristi",
      "Ángel Pedro Giler",
      "El Colorado",
      "Guale",
      "Jaramijó",
      "La Pila",
      "Pile",
    ],
    Paján: ["Paján", "Campozano", "Cascol", "Guale", "Lascano"],
    Pichincha: ["Pichincha", "Barraganete", "San Sebastián"],
    Rocafuerte: ["Rocafuerte"],
    "Santa Ana": [
      "Santa Ana",
      "Ayacucho",
      "Lodana",
      "Olmedo",
      "San Pablo de Pueblo Nuevo",
    ],
    Sucre: [
      "Bahía de Caráquez",
      "Charapotó",
      "Chiesa",
      "Leónidas Plaza",
      "San Isidro",
      "San Jacinto",
      "San Clemente",
    ],
    Tosagua: ["Tosagua", "Bachillero", "Ángel Pedro Giler"],
    "24 de Mayo": ["Sucre", "Bellavista", "Noboa"],
    Pedernales: ["Pedernales", "Atahualpa", "Cojimíes", "10 de Agosto"],
    Olmedo: ["Olmedo"],
    "Puerto López": ["Puerto López", "Machalilla", "Salango"],
    Jama: ["Jama"],
    Jaramijó: ["Jaramijó"],
    "San Vicente": ["San Vicente", "Canoa"],
    // eslint-disable-next-line no-dupe-keys
    Olmedo: ["Olmedo"],
    // eslint-disable-next-line no-dupe-keys
    Bolívar: ["Bolívar", "Calceta", "Membrillo", "Quiroga"],
  },

  "Morona Santiago": {
    Morona: [
      "Macas",
      "Alshi",
      "Cuchaentza",
      "General Proaño",
      "Huasaga",
      "Macuma",
      "San Isidro",
      "Sevilla Don Bosco",
      "Sinaí",
      "Taisha",
      "Tuutinentza",
      "Zuña",
    ],
    Gualaquiza: [
      "Gualaquiza",
      "Amazonas",
      "Bermejos",
      "Bomboiza",
      "Chigüinda",
      "El Rosario",
      "Nueva Tarqui",
    ],
    "Limón Indanza": [
      "General Leonidas Plaza Gutiérrez",
      "Indanza",
      "San Antonio",
      "San Carlos",
      "San Juan Bosco",
      "Santa Susana de Chiviaza",
    ],
    Palora: ["Palora", "Arapicos", "Cumandá", "Huamboya", "Sangay"],
    Santiago: [
      "Santiago de Méndez",
      "Copal",
      "Chupianza",
      "Patuca",
      "San Luis de El Acho",
      "Santa Marianita de Jesús",
      "Tayuza",
    ],
    Sucúa: [
      "Sucúa",
      "Asunción",
      "Huambi",
      "Logroño",
      "Santa Marianita de Jesús",
    ],
    Huamboya: ["Huamboya", "Chiguaza", "Pablo Sexto"],
    "San Juan Bosco": [
      "San Juan Bosco",
      "Pan de Azúcar",
      "San Carlos de Limón",
      "San Jacinto de Wakambeis",
      "Santiago de Pananza",
    ],
    Taisha: ["Taisha", "Huasaga", "Macuma", "Pumpuentsa", "Tuutinentza"],
    Logroño: ["Logroño", "Shimpis", "Yaupi"],
    "Pablo Sexto": ["Pablo Sexto"],
    Tiwintza: ["Santiago", "San José de Morona"],
  },

  Napo: {
    Tena: [
      "Tena",
      "Ahuano",
      "Carlos Julio Arosemena Tola",
      "Chontapunta",
      "Misahuallí",
      "Pano",
      "Puerto Misahuallí",
      "Puerto Napo",
      "Pusuno",
      "San Juan de Muyuna",
      "Talag",
    ],
    Archidona: [
      "Archidona",
      "Avila",
      "Cotundo",
      "Loreto",
      "San Pablo de Ushpayacu",
    ],
    "El Chaco": [
      "El Chaco",
      "Gonzalo Díaz de Pineda",
      "Linares",
      "Oyacachi",
      "Santa Rosa",
      "Sardinas",
    ],
    Quijos: [
      "Baeza",
      "Cosanga",
      "Cuyuja",
      "Papallacta",
      "San Francisco de Borja",
      "Sumaco",
    ],
    "Carlos Julio Arosemena Tola": ["Carlos Julio Arosemena Tola"],
  },

  Orellana: {
    Orellana: [
      "Puerto Francisco de Orellana",
      "Dayuma",
      "El Dorado",
      "García Moreno",
      "Guayusa",
      "Inés Arango",
      "La Belleza",
      "Nuevo Paraíso",
      "San José de Guayusa",
      "San Luis de Armenia",
      "Taracoa",
    ],
    Aguarico: [
      "Nuevo Rocafuerte",
      "Capitán Augusto Rivadeneyra",
      "Cononaco",
      "Santa María de Huiririma",
      "Tiputini",
      "Yasuní",
    ],
    "La Joya de los Sachas": [
      "La Joya de los Sachas",
      "Enokanqui",
      "Pompeya",
      "San Carlos",
      "San Sebastián del Coca",
      "Lago San Pedro",
      "Rumipamba",
      "Tres de Noviembre",
      "Unión Milagreña",
    ],
    Loreto: [
      "Loreto",
      "Avila",
      "Puerto Murialdo",
      "San José de Payamino",
      "San José de Dahuano",
      "San Vicente de Huaticocha",
    ],
  },

  Pastaza: {
    Pastaza: [
      "Puyo",
      "Canelos",
      "Diez de Agosto",
      "Fátima",
      "Montalvo",
      "Pomona",
      "Río Corrientes",
      "Río Tigre",
      "San José",
      "Simón Bolívar",
      "Tarqui",
      "Teniente Hugo Ortiz",
      "Veracruz",
    ],
    Mera: ["Mera", "Madre Tierra", "Shell"],
    "Santa Clara": ["Santa Clara", "San José"],
    Arajuno: ["Arajuno", "Curaray"],
  },

  Pichincha: {
    Quito: [
      "Quito",
      "Alangasí",
      "Amaguaña",
      "Atahualpa",
      "Calacalí",
      "Calderón",
      "Conocoto",
      "Cumbayá",
      "Chavezpamba",
      "Checa",
      "El Quinche",
      "Gualea",
      "Guangopolo",
      "Guayllabamba",
      "La Merced",
      "Llano Chico",
      "Lloa",
      "Nanegal",
      "Nanegalito",
      "Nayón",
      "Nono",
      "Pacto",
      "Pedro Vicente Maldonado",
      "Perucho",
      "Pifo",
      "Píntag",
      "Pomasqui",
      "Puéllaro",
      "Puembo",
      "San Antonio",
      "San José de Minas",
      "San Miguel de los Bancos",
      "Tababela",
      "Tumbaco",
      "Yaruquí",
      "Zambiza",
    ],
    Cayambe: [
      "Cayambe",
      "Ascázubi",
      "Cangahua",
      "Olmedo",
      "Otón",
      "Santa Rosa de Cuzubamba",
      "Juan Montalvo",
    ],
    Mejía: [
      "Machachi",
      "Alóag",
      "Aloasí",
      "Cutuglahua",
      "El Chaupi",
      "Manuel Cornejo Astorga",
      "Tambillo",
      "Uyumbicho",
    ],
    "Pedro Moncayo": [
      "Tabacundo",
      "La Esperanza",
      "Malchinguí",
      "Tocachi",
      "Tupigachi",
    ],
    Rumiñahui: [
      "Sangolquí",
      "Cotogchoa",
      "Rumipamba",
      "San Pedro de Taboada",
      "San Rafael",
    ],
    "San Miguel de los Bancos": [
      "San Miguel de los Bancos",
      "Mindo",
      "Pedro Vicente Maldonado",
    ],
    "Pedro Vicente Maldonado": ["Pedro Vicente Maldonado"],
    "Puerto Quito": ["Puerto Quito"],
  },

  "Santa Elena": {
    "Santa Elena": [
      "Santa Elena",
      "Atahualpa",
      "Ballenita",
      "Chanduy",
      "Colonche",
      "Manglaralto",
      "Simón Bolívar",
      "San José de Ancón",
    ],
    "La Libertad": ["La Libertad"],
    Salinas: ["Salinas", "Anconcito", "José Luis Tamayo"],
  },

  "Santo Domingo de los Tsáchilas": {
    "Santo Domingo": [
      "Santo Domingo de los Colorados",
      "Alluriquín",
      "Luz de América",
      "Puerto Limón",
      "San Jacinto del Búa",
      "Valle Hermoso",
      "El Esfuerzo",
      "Santa María del Toachi",
    ],
  },

  Sucumbíos: {
    "Lago Agrio": [
      "Nueva Loja",
      "Dureno",
      "General Farfán",
      "El Eno",
      "Pacayacu",
      "Jambelí",
      "Santa Cecilia",
    ],
    Cascales: ["El Dorado de Cascales", "Santa Rosa de Sucumbíos", "Sevilla"],
    Cuyabeno: ["Tarapoa", "Aguas Negras", "Cuyabeno"],
    "Gonzalo Pizarro": [
      "Lumbaquí",
      "El Reventador",
      "González Pizarro",
      "Puerto Libre",
    ],
    Putumayo: [
      "Puerto El Carmen de Putumayo",
      "Palma Roja",
      "Puerto Bolívar",
      "Puerto Rodríguez",
      "Santa Elena",
    ],
    Shushufindi: [
      "Shushufindi",
      "Limoncocha",
      "Pañacocha",
      "San Roque",
      "San Pedro de los Cofanes",
      "Siete de Julio",
    ],
    Sucumbíos: [
      "La Bonita",
      "El Playón de San Francisco",
      "La Sofía",
      "Rosa Florida",
      "Santa Bárbara",
    ],
  },

  Tungurahua: {
    Ambato: [
      "Ambato",
      "Ambatillo",
      "Atahualpa",
      "Augusto N. Martínez",
      "Constantino Fernández",
      "Huachi Grande",
      "Izamba",
      "Juan Benigno Vela",
      "Montalvo",
      "Pasa",
      "Picaigua",
      "Pilagüín",
      "Quisapincha",
      "San Bartolomé de Pinllo",
      "San Fernando",
      "Santa Rosa",
      "Totoras",
      "Unamuncho",
    ],
    "Baños de Agua Santa": [
      "Baños de Agua Santa",
      "Lligua",
      "Río Negro",
      "Río Verde",
      "Ulba",
    ],
    Cevallos: ["Cevallos"],
    Mocha: ["Mocha", "Pinguilí"],
    Patate: ["Patate", "El Triunfo", "Los Andes", "Sucre"],
    Quero: ["Quero", "Rumipamba", "Yanayacu"],
    "San Pedro de Pelileo": [
      "Pelileo",
      "Benítez",
      "Bolívar",
      "Cotaló",
      "Chiquicha",
      "El Rosario",
      "García Moreno",
      "Guambaló",
      "Salasaca",
    ],
    "Santiago de Píllaro": [
      "Píllaro",
      "Baquerizo Moreno",
      "Emilio María Terán",
      "Marcos Espinel",
      "Presidente Urbina",
      "San Andrés",
      "San José de Poaló",
      "San Miguelito",
    ],
    Tisaleo: ["Tisaleo", "Quinchicoto"],
  },

  "Zamora Chinchipe": {
    Zamora: [
      "Zamora",
      "Cumbaratza",
      "Guadalupe",
      "Imbana",
      "Sabanilla",
      "Timbara",
      "San Carlos de las Minas",
    ],
    Chinchipe: [
      "Zumba",
      "Chito",
      "El Chorro",
      "La Chonta",
      "Pucapamba",
      "San Andrés",
    ],
    Nangaritza: ["Guayzimi", "Zurmi", "Nuevo Paraíso"],
    Yacuambi: ["28 de Mayo", "La Paz", "Tutupali"],
    Yantzaza: ["Yantzaza", "Chicaña", "El Pangui", "Los Encuentros"],
    "El Pangui": ["El Pangui", "El Guismi", "Pachicutza", "Tundayme"],
    "Centinela del Cóndor": ["Zumbi", "Triunfo-Dorado", "Panguintza"],
    Palanda: [
      "Palanda",
      "El Porvenir del Carmen",
      "San Francisco del Vergel",
      "Valladolid",
      "La Canela",
    ],
    Paquisha: ["Paquisha", "Bellavista", "Nuevo Quito"],
  },

  Galápagos: {
    "San Cristóbal": ["Puerto Baquerizo Moreno", "El Progreso"],
    Isabela: ["Puerto Villamil", "Tomás de Berlanga"],
    "Santa Cruz": ["Puerto Ayora", "Bellavista", "Santa Rosa"],
  },
};

function getProvincias() {
  return Object.keys(ecuadorLocations);
}

function getCantones(provincia) {
  return ecuadorLocations[provincia]
    ? Object.keys(ecuadorLocations[provincia])
    : [];
}

function getParroquias(provincia, canton) {
  return ecuadorLocations[provincia] && ecuadorLocations[provincia][canton]
    ? ecuadorLocations[provincia][canton]
    : [];
}

export { ecuadorLocations, getProvincias, getCantones, getParroquias };
